BEGIN TRANSACTION;

INSERT INTO brewer(username, brewer_name) VALUES ('aaronschickel','Aaron Schickel');
INSERT INTO brewer(username, brewer_name) VALUES ('andytveekrem','Andy Tveekrem');
INSERT INTO brewer(username, brewer_name) VALUES ('annzofchak','Ann Zofchak');
INSERT INTO brewer(username, brewer_name) VALUES ('chriskambouris','Chris Kambouris');
INSERT INTO brewer(username, brewer_name) VALUES ('danblatt','Dan Blatt');
INSERT INTO brewer(username, brewer_name) VALUES ('ericanderson','Eric Anderson');
INSERT INTO brewer(username, brewer_name) VALUES ('erikluli','Erik Luli');
INSERT INTO brewer(username, brewer_name) VALUES ('gavinrousek','Gavin Rousek');
INSERT INTO brewer(username, brewer_name) VALUES ('gregirving','Greg Irving');
INSERT INTO brewer(username, brewer_name) VALUES ('jackkephart','Jack Kephart');
INSERT INTO brewer(username, brewer_name) VALUES ('jamesmackay','James MacKay');
INSERT INTO brewer(username, brewer_name) VALUES ('jameswatt','James Watt');
INSERT INTO brewer(username, brewer_name) VALUES ('jasoncomeaux','Jason Comeaux');
INSERT INTO brewer(username, brewer_name) VALUES ('jasonslater','Jason Slater');
INSERT INTO brewer(username, brewer_name) VALUES ('jasonsweet','Jason Sweet');
INSERT INTO brewer(username, brewer_name) VALUES ('jaycox','Jay Cox');
INSERT INTO brewer(username, brewer_name) VALUES ('jeromemoore','Jerome Moore');
INSERT INTO brewer(username, brewer_name) VALUES ('joelwarger','Joel Warger');
INSERT INTO brewer(username, brewer_name) VALUES ('johnmcgroarty','John McGroarty');
INSERT INTO brewer(username, brewer_name) VALUES ('joshjones','Josh Jones');
INSERT INTO brewer(username, brewer_name) VALUES ('karlspiesman','Karl Spiesman');
INSERT INTO brewer(username, brewer_name) VALUES ('keithclapper','Keith Clapper');
INSERT INTO brewer(username, brewer_name) VALUES ('lawrenceesper','Lawrence Esper');
INSERT INTO brewer(username, brewer_name) VALUES ('lucaspurcell','Lucas Purcell');
INSERT INTO brewer(username, brewer_name) VALUES ('markhunger','Mark Hunger');
INSERT INTO brewer(username, brewer_name) VALUES ('mathiashauck','Mathias Hauck');
INSERT INTO brewer(username, brewer_name) VALUES ('mattcole','Matt Cole');
INSERT INTO brewer(username, brewer_name) VALUES ('mattsmedley','Matt Smedley');
INSERT INTO brewer(username, brewer_name) VALUES ('michaelpelechaty','Michael Pelechaty');
INSERT INTO brewer(username, brewer_name) VALUES ('petervelez','Peter Velez');
INSERT INTO brewer(username, brewer_name) VALUES ('ralphsgro','Ralph Sgro');
INSERT INTO brewer(username, brewer_name) VALUES ('richardskains','Richard Skains');
INSERT INTO brewer(username, brewer_name) VALUES ('sarahjackson','Sarah Jackson');
INSERT INTO brewer(username, brewer_name) VALUES ('shaunyasaki','Shaun Yasaki');
INSERT INTO brewer(username, brewer_name) VALUES ('stevekessler','Steve Kessler');
INSERT INTO brewer(username, brewer_name) VALUES ('vaughnstewart','Vaughn Stewart');
INSERT INTO brewer(username, brewer_name) VALUES ('wyattroutson','Wyatt Routson');
INSERT INTO brewer(username, brewer_name) VALUES ('zechlaughbaum','Zech Laughbaum');

COMMIT TRANSACTION;