BEGIN TRANSACTION;

INSERT INTO users (username, password_hash, role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username, password_hash, role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');
INSERT INTO users (username, password_hash, role) VALUES ('aaronschickel','$2a$10$U1yFu/5wNKNZ4dlLUSy2OeI85BfpH7PKTXEXZPY5q1hqfSHqS7.gq','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('andytveekrem','$2a$10$yT.YM17sJ0dY73Qbf.mMleyH1QOd8cAEBIu7z7faegUmNYKabY0Za','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('annzofchak','$2a$10$KlylF1cefBXEhFPStI8.0.QVF5YIb0l84onP9onoqTzHbHgz/rRsq','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('chriskambouris','$2a$10$czX9IDjhItzmUyDBz9yW2umTguqnA.4PpF0grGvyG0AZw.L42Hqb.','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('danblatt','$2a$10$.GNOqHNZrdhJl8AbbkZG1.3jlkB0kLryS969Rlx9Wh0EQ06RWubuG','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('ericanderson','$2a$10$gpDVYyW7QHwcT/RypcjY8ey8BoTFqN9ITnLoXlSh3SOGkFIIDXVuK','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('erikluli','$2a$10$jl39EHnMcKTJLCk80F1XSuNj92pMUOdogpjOCcqCjoKKmjxKHuHVm','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('gavinrousek','$2a$10$kB959OZAuP7j/1ZDQBYMl.NHS9AWislzesXPPP6ZxxEce3ghG3kfO','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('gregirving','$2a$10$Ar6JIQ0R5NV.ZXnZTu1fU.fWD8t2PlmoJm2ugVu5sWhM6C6gr0x/a','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('jackkephart','$2a$10$Xz3Qi9mArTV1Xo5yrYPJ7OaGC7L1favzFz.clS57SBmbjTq/KmWwW','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('jamesmackay','$2a$10$Z8iucdW/QudJzDWwecZK2uSSOl7hSVK/DFAxz07s6eDPYP90TYZcy','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('jameswatt','$2a$10$A6yGAN.dr.oFO92GBu4D6e2xazYT5H2FmXWmMJLmrPbN7I.gIAJlq','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('jasoncomeaux','$2a$10$GhvCtMXz4nYXNERlh9w0w.fMQy3oId3R/hh5EqTbZbHJ0453huF2u','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('jasonslater','$2a$10$hSjWbdGfuYq0xsmQZ4Ycl.ykTaaZttYb9TBx/tVg5Fe6Z9.DmJbBG','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('jasonsweet','$2a$10$n8XrCgsQ2kmP9n87ofJvS.QvU8r2NOWvEh4601KRe11jNO7k6d02y','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('jaycox','$2a$10$bTC/HQHCQ.Xmn3ZiUfQlS.fXF5CA/irx/nIxmazv0ntxv/1VZmNH6','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('jeromemoore','$2a$10$u0sEgvX52FmhzcPoZeRf6u6xT4BsP66vNLS2ANs0.xPnSVw7.Gdsq','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('joelwarger','$2a$10$bk/Gmwgd1csGkjL5ko8eD.JY75wQ.HKIfLUhAIf5VeIoCokAxDB.O','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('johnmcgroarty','$2a$10$TBfWUh7j4tu6CQndco0OQ.swCA.fYl.fBTLe57fkJ6Z/ihmaHP21W','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('joshjones','$2a$10$.xsDI9rw4kiOtSPHSBmOo.bIRTvcEbmZ2lvUIQMZ2OZcKe7xiLoRi','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('karlspiesman','$2a$10$ytypngt0AlaJKbmRS7S.T.wy4gkK2HFPj9kvsy4W0g1oP5rr2nwUK','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('keithclapper','$2a$10$cfcc9FL36NfDif2lzfMjOOShDIShdjWw3MyfXV5njIAVfXoZvHPTO','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('lawrenceesper','$2a$10$3T9B/.A/t/2P5RbrWIoUfehY/vjDZb9ilOahoE106k.avX3/3fg8u','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('lucaspurcell','$2a$10$zRicXyvL/mKMaHYtEPZMuO/o33iz4NG0fkbM49mLl2bSM6I.R.TGS','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('markhunger','$2a$10$q64J025WDSZodcFDM6Lq/uaUyZxv8Lz67aASw5Ctg8HoPFuL/Su2S','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('mathiashauck','$2a$10$wSiFvP77vm/7H7d1r0KxHONjFSKYf02DTLXQKc0TlZCZ9Xf.Hco36','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('mattcole','$2a$10$xAdUi7Zm.Ls3zmwoZ46eC.TbqY6FLwKhXhtbQromg55A3RLRtn4Lm','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('mattsmedley','$2a$10$lJHMdwRx2tOBllHnjDyVMOlIo2OdXtRK2gvC2Ewx0yFEs7U59q44i','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('michaelpelechaty','$2a$10$a9IjykfnShRamp5SAbKbn.0gYdxNrZT1b0nUN4iidcNcTNZWzf89.','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('petervelez','$2a$10$l3NB3Je8tD6BJpalisgQmOFXq/a8C1srrNOakByTVdHlnf.UsO.za','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('ralphsgro','$2a$10$Y9BmEDU2q0zhTrYi.PKb5uJjiQPQBw2Wsb.ECHrknqxujTF/Nkzq.','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('richardskains','$2a$10$ha/0xUQ2xRSwKfeKrGJbduMXwAybyRHrQF1Wulb.jZBoN0x.M1O6e','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('sarahjackson','$2a$10$/qF05zUVOINjupd7xDtlo.Ke7ynMz7e0vZcVwbRlvvK0UD/ekNoeG','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('shaunyasaki','$2a$10$.jc2LEpSUmLTB60ElwpXDu/pmZCLpvckMpnxFxW/LVF4oJgmPF0S2','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('stevekessler','$2a$10$AtLmAM4pAv.du.poD1wBCuZPTcA2Dg7LetuRyaXAy03vmiiC8ZhO.','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('vaughnstewart','$2a$10$xoXDtq1N7MMSfR3EYfHmP.b2f9ui5BVIjQGWk4eWBr9BoKFGW1hBm','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('wyattroutson','$2a$10$rHAZwV2CZg7swkShiK7eBurlDTUi9CYYwNPmqys.n.9s2BMFzSFOS','ROLE_BREWER');
INSERT INTO users (username, password_hash, role) VALUES ('zechlaughbaum','$2a$10$ogNDRtq/ZST39Ydt9pdI5eaGV14zUVCeBYBl8R47Kiw5n7hZ/urG.','ROLE_BREWER');

COMMIT TRANSACTION;